#!/usr/bin/env python3
import os
import datetime

# Correct CGI headers
print("Content-Type: text/html\r\n\r\n")

# Get some dynamic info
request_method = os.getenv("REQUEST_METHOD", "UNKNOWN")
script_name = os.getenv("SCRIPT_NAME", "UNKNOWN")
server_software = os.getenv("SERVER_SOFTWARE", "WebServer/1.0")
current_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

# HTML content
html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CGI Super Page 🚀</title>
<style>
    body {{
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background: linear-gradient(135deg, #f0f4ff, #d9e4ff);
        color: #1a1a1a;
        margin: 0;
        padding: 0;
    }}
    header {{
        background: #4b6cb7;
        color: white;
        padding: 1.5rem;
        text-align: center;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
    }}
    nav {{
        text-align: center;
        margin: 1rem 0;
    }}
    nav a {{
        margin: 0 1rem;
        text-decoration: none;
        color: #4b6cb7;
        font-weight: bold;
    }}
    nav a:hover {{
        color: #182848;
        text-decoration: underline;
    }}
    section {{
        max-width: 800px;
        margin: 2rem auto;
        padding: 1rem 2rem;
        background: white;
        border-radius: 10px;
        box-shadow: 0 4px 10px rgba(0,0,0,0.1);
    }}
    footer {{
        text-align: center;
        padding: 1rem;
        background: #f0f4ff;
        color: #555;
        border-top: 1px solid #ccc;
        margin-top: 2rem;
    }}
</style>
</head>
<body>
<header>
    <h1>Welcome to my CGI Page! 🚀 </h1>
</header>

<nav>
    <a href="/">Home</a>
    <a href="/upload">Upload</a>
    <a href="/cgi-bin">CGI</a>
    <a href="/nonexistent">404</a>
</nav>

<section>
    <h2>Server & Request Info</h2>
    <p><strong>Request Method:</strong> {request_method}</p>
    <p><strong>Script Name:</strong> {script_name}</p>
    <p><strong>Server Software:</strong> {server_software}</p>
    <p><strong>Current Time:</strong> {current_time}</p>
</section>

<section>
    <h2>About This CGI Page</h2>
    <p>This page is dynamically generated by a Python CGI script. It demonstrates:</p>
    <ul>
        <li>Correct HTTP headers for CGI</li>
        <li>Dynamic server information</li>
        <li>Responsive and modern HTML styling</li>
        <li>Navigation links for testing routes</li>
    </ul>
</section>

<footer>
    <p>&copy; {datetime.datetime.now().year} My Web Server | Powered by Python CGI</p>
</footer>
</body>
</html>
"""

print(html)
